# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12vSH6yCiPIjmXMn3cW0TgB3Vggf0x2Bb
"""

D1 = float(input())
V1 = float(input())
T  = float(input())
D2 = float(input())
V2 = float(input())

T1 = D1/V1/24
T2 = (D2/V2/24)+T

if T1<T2:
  print('True')
else:
  print('False')





